global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'monitoring_dashboard'
    static_configs:
      - targets: ['system-monitoring-dashboard-1:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'production_server'
    static_configs:
      - targets: ['system-monitoring-production-server-1:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'development_server'
    static_configs:
      - targets: ['system-monitoring-development-server-1:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s 